az2                 = "us-west-2c"
subnet-suffix       = "c" 
role2               = "kafka-zookeeper-node"
purpose2            = "kafka-zookeeper-node"
region              = "us-west-2"
inboundport         = "2081"
machine-ami         = "my-linux-ami"
